
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyjmfinhleizpxqedeku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5am1maW5obGVpenB4cWVkZWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDMwOTcsImV4cCI6MjA1ODQxOTA5N30.QIrPaJhE9V2yWANsBErkR3r9IEpDAnPRokf7Wy37kIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    db: {
      schema: 'public',
    }
  }
);
